<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
return [
		'index'=>['title'=>'分类管理','sub'=>
			[
				['title'=>'视频','sub'=>
					[
						['title'=>'分类管理','uri'=>'admin/category','params'=>['type'=>1]],
					]
				],
				['title'=>'音频','sub'=>
					[
						['title'=>'分类管理','uri'=>'admin/category','params'=>['type'=>2]],
					]
				],
			]
		],
		'content'=>['title'=>'内容管理','sub'=>
			[
				['title'=>'视频管理','sub'=>
					[
						['title'=>'添加视频','uri'=>'admin/video/edit'],
						['title'=>'视频列表','uri'=>'admin/video'],
					]
				],
				['title'=>'音频管理','sub'=>
					[
						['title'=>'添加音频','uri'=>'admin/audio/edit'],
						['title'=>'音频列表','uri'=>'admin/audio'],
					]
				],
			]
		]
	];